version: '3.8'

services:
  # Backend service (ASP.NET Core)
  backend:
    image: your-backend-image:latest  # Replace with your BE Docker image
    container_name: attech-backend
    ports:
      - "7276:7276"  # Expose backend on port 7276
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7276
    networks:
      - attech-network
    restart: unless-stopped

  # Frontend service (React + Nginx)
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: attech-frontend
    ports:
      - "80:80"      # Frontend on port 80
      - "443:443"    # HTTPS if needed
    depends_on:
      - backend
    networks:
      - attech-network
    restart: unless-stopped

networks:
  attech-network:
    driver: bridge