export const mockNews = [
  {
    id: 1,
    titleVi: "Hội nghị Công đoàn năm 2024",
    slugVi: "hoi-nghi-cong-doan-nam-2024",
    descriptionVi: "Hội nghị Công đoàn công ty đã diễn ra thành công...",
    contentVi: "Nội dung chi tiết bằng tiếng Việt...",
    titleEn: "Union Conference 2024",
    slugEn: "union-conference-2024",
    descriptionEn: "The company's union conference was successfully held...",
    contentEn: "Detailed content in English...",
    timePosted: "2024-01-15T00:00:00Z",
    status: 1,
    postCategoryId: 14,
    postCategoryNameVi: "Công đoàn công ty",
    postCategoryNameEn: "Company Union",
    postCategorySlugVi: "cong-doan-cong-ty",
    postCategorySlugEn: "company-union",
    image: "https://picsum.photos/300/200?random=1"
  },
  {
    id: 2,
    titleVi: "Đại hội Đảng bộ lần thứ 15",
    slugVi: "dai-hoi-dang-bo-lan-thu-15",
    descriptionVi: "Đại hội Đảng bộ công ty lần thứ 15 đã được tổ chức với nhiều quyết sách quan trọng...",
    contentVi: "Nội dung chi tiết bằng tiếng Việt...",
    titleEn: "15th Party Committee Meeting",
    slugEn: "15th-party-committee-meeting",
    descriptionEn: "The company's 15th party committee meeting was held with many important decisions...",
    contentEn: "Detailed content in English...",
    timePosted: "2024-01-20T00:00:00Z",
    status: 1,
    postCategoryId: 12,
    postCategoryNameVi: "Đảng bộ công ty",
    postCategoryNameEn: "Company Party",
    postCategorySlugVi: "dang-bo-cong-ty",
    postCategorySlugEn: "company-party",
    image: "https://picsum.photos/300/200?random=2"
  },
  {
    id: 3,
    titleVi: "Hoạt động tình nguyện mùa hè",
    slugVi: "hoat-dong-tinh-nguyen-mua-he",
    descriptionVi: "Các hoạt động tình nguyện mùa hè đã được tổ chức tại nhiều địa phương...",
    contentVi: "Nội dung chi tiết bằng tiếng Việt...",
    titleEn: "Volunteer Activities in Summer",
    slugEn: "volunteer-activities-in-summer",
    descriptionEn: "Volunteer activities in summer were organized in various locations...",
    contentEn: "Detailed content in English...",
    timePosted: "2024-02-10T00:00:00Z",
    status: 1,
    postCategoryId: 10,
    postCategoryNameVi: "Tin hoạt động",
    postCategoryNameEn: "Activities",
    postCategorySlugVi: "tin-hoat-dong",
    postCategorySlugEn: "activities",
    image: "https://picsum.photos/300/200?random=3"
  },
  {
    id: 4,
    titleVi: "Giải bóng đá nội bộ 2024",
    slugVi: "giai-bong-da-noi-bo-2024",
    descriptionVi: "Giải bóng đá nội bộ công ty năm 2024 đã thu hút sự tham gia của 8 đội bóng...",
    contentVi: "Nội dung chi tiết bằng tiếng Việt...",
    titleEn: "2024 Company Football Tournament",
    slugEn: "2024-company-football-tournament",
    descriptionEn: "The 2024 company football tournament attracted 8 teams...",
    contentEn: "Detailed content in English...",
    timePosted: "2024-02-15T00:00:00Z",
    status: 1,
    postCategoryId: 11,
    postCategoryNameVi: "Hoạt động công ty",
    postCategoryNameEn: "Company Activities",
    postCategorySlugVi: "hoat-dong-cong-ty",
    postCategorySlugEn: "company-activities",
    image: "https://picsum.photos/300/200?random=4"
  },
  {
    id: 5,
    titleVi: "Nghiên cứu mới về công nghệ AI",
    slugVi: "nghien-cuu-moi-ve-cong-nghe-ai",
    descriptionVi: "Nhóm nghiên cứu của công ty đã công bố những phát hiện mới về ứng dụng AI...",
    contentVi: "Nội dung chi tiết bằng tiếng Việt...",
    titleEn: "New AI Research",
    slugEn: "new-ai-research",
    descriptionEn: "The company's AI research group has announced new discoveries in AI applications...",
    contentEn: "Detailed content in English...",
    timePosted: "2024-02-20T00:00:00Z",
    status: 1,
    postCategoryId: 15,
    postCategoryNameVi: "Tin ngành hàng không",
    postCategoryNameEn: "Aviation News",
    postCategorySlugVi: "tin-nganh-hang-khong",
    postCategorySlugEn: "aviation-news",
    image: "https://picsum.photos/300/200?random=5"
  },
  {
    id: 6,
    titleVi: "Cập nhật hệ thống quản lý mới",
    slugVi: "cap-nhat-he-thong-quan-ly-moi",
    descriptionVi: "Công ty đã triển khai hệ thống quản lý mới với nhiều tính năng hiện đại...",
    contentVi: "Nội dung chi tiết bằng tiếng Việt...",
    titleEn: "New Management System Update",
    slugEn: "new-management-system-update",
    descriptionEn: "The company has rolled out a new management system with many modern features...",
    contentEn: "Detailed content in English...",
    timePosted: "2024-02-25T00:00:00Z",
    status: 1,
    postCategoryId: 15,
    postCategoryNameVi: "Tin ngành hàng không",
    postCategoryNameEn: "Aviation News",
    postCategorySlugVi: "tin-nganh-hang-khong",
    postCategorySlugEn: "aviation-news",
    image: "https://picsum.photos/300/200?random=6"
  },
  {
    id: 7,
    titleVi: "Chương trình đào tạo nhân viên",
    slugVi: "chuong-trinh-dao-tao-nhan-vien",
    descriptionVi: "Chương trình đào tạo nhân viên mới đã được khởi động với nhiều khóa học bổ ích...",
    contentVi: "Nội dung chi tiết bằng tiếng Việt...",
    titleEn: "New Employee Training Program",
    slugEn: "new-employee-training-program",
    descriptionEn: "The company's new employee training program has been launched with many useful courses...",
    contentEn: "Detailed content in English...",
    timePosted: "2024-03-01T00:00:00Z",
    status: 1,
    postCategoryId: 13,
    postCategoryNameVi: "Đoàn thanh niên công ty",
    postCategoryNameEn: "Company Youth Union",
    postCategorySlugVi: "doan-thanh-nien-cong-ty",
    postCategorySlugEn: "company-youth-union",
    image: "https://picsum.photos/300/200?random=7"
  },
  {
    id: 8,
    titleVi: "Khám sức khỏe định kỳ 2024",
    slugVi: "kham-suc-khoe-dinh-ky-2024",
    descriptionVi: "Chương trình khám sức khỏe định kỳ cho toàn thể nhân viên đã được tổ chức...",
    contentVi: "Nội dung chi tiết bằng tiếng Việt...",
    titleEn: "Annual Health Checkup 2024",
    slugEn: "annual-health-checkup-2024",
    descriptionEn: "The annual health checkup for all employees has been organized...",
    contentEn: "Detailed content in English...",
    timePosted: "2024-03-05T00:00:00Z",
    status: 1,
    postCategoryId: 17,
    postCategoryNameVi: "Y tế sức khỏe",
    postCategoryNameEn: "Healthcare",
    postCategorySlugVi: "yte-suc-khoe",
    postCategorySlugEn: "healthcare",
    image: "https://picsum.photos/300/200?random=8"
  },
  {
    id: 9,
    titleVi: "Hội thảo về phát triển bền vững",
    slugVi: "hoi-thao-ve-phat-trien-ben-vung",
    descriptionVi: "Hội thảo về phát triển bền vững đã thu hút sự quan tâm của nhiều chuyên gia...",
    contentVi: "Nội dung chi tiết bằng tiếng Việt...",
    titleEn: "Sustainable Development Symposium",
    slugEn: "sustainable-development-symposium",
    descriptionEn: "The sustainable development symposium attracted the attention of many experts...",
    contentEn: "Detailed content in English...",
    timePosted: "2024-03-10T00:00:00Z",
    status: 1,
    postCategoryId: 10,
    postCategoryNameVi: "Tin hoạt động",
    postCategoryNameEn: "Activities",
    postCategorySlugVi: "tin-hoat-dong",
    postCategorySlugEn: "activities",
    image: "https://picsum.photos/300/200?random=9"
  },
  {
    id: 10,
    titleVi: "Giải chạy bộ vì sức khỏe",
    slugVi: "giai-chay-bo-vi-suc-khoe",
    descriptionVi: "Giải chạy bộ vì sức khỏe đã thu hút hơn 500 người tham gia...",
    contentVi: "Nội dung chi tiết bằng tiếng Việt...",
    titleEn: "Run for Health Race",
    slugEn: "run-for-health-race",
    descriptionEn: "The run for health race attracted more than 500 participants...",
    contentEn: "Detailed content in English...",
    timePosted: "2024-03-15T00:00:00Z",
    status: 1,
    postCategoryId: 11,
    postCategoryNameVi: "Hoạt động công ty",
    postCategoryNameEn: "Company Activities",
    postCategorySlugVi: "hoat-dong-cong-ty",
    postCategorySlugEn: "company-activities",
    image: "https://picsum.photos/300/200?random=10"
  }
]; 