export const mockNotifications = [
  {
    id: 1,
    titleVi: "Thông báo tuyển dụng tháng 5",
    slugVi: "thong-bao-tuyen-dung-thang-5",
    titleEn: "May Recruitment Notice",
    slugEn: "may-recruitment-notice",
    descriptionVi: "Công ty thông báo tuyển dụng nhân sự tháng 5 với nhiều vị trí hấp dẫn...",
    descriptionEn: "The company announces May recruitment with many attractive positions...",
    contentVi: "Nội dung chi tiết thông báo tuyển dụng bằng tiếng Việt...",
    contentEn: "Detailed recruitment notice content in English...",
    timePosted: "2024-05-01T00:00:00Z",
    status: 1,
    notificationCategoryId: 1,
    notificationCategoryNameVi: "Tuyển dụng",
    notificationCategoryNameEn: "Recruitment",
    notificationCategorySlugVi: "tuyen-dung",
    notificationCategorySlugEn: "recruitment",
    image: "https://picsum.photos/300/200?random=301"
  },
  {
    id: 2,
    titleVi: "Thông báo về việc cập nhật hệ thống nội bộ",
    slugVi: "thong-bao-ve-viec-cap-nhat-he-thong-noi-bo",
    titleEn: "Internal System Update Notice",
    slugEn: "internal-system-update-notice",
    descriptionVi: "Hệ thống quản lý nội bộ sẽ được cập nhật vào ngày 15/1/2024 từ 22:00 đến 02:00...",
    descriptionEn: "The internal management system will be updated on January 15, 2024 from 22:00 to 02:00...",
    contentVi: "Nội dung chi tiết thông báo cập nhật hệ thống bằng tiếng Việt...",
    contentEn: "Detailed system update notice content in English...",
    timePosted: "2024-01-15T00:00:00Z",
    status: 1,
    notificationCategoryId: 3,
    notificationCategoryNameVi: "Thông báo nội bộ",
    notificationCategoryNameEn: "Internal Notice",
    notificationCategorySlugVi: "thong-bao-noi-bo",
    notificationCategorySlugEn: "internal-notice",
    image: "https://picsum.photos/300/200?random=302"
  },
  {
    id: 3,
    titleVi: "Thông báo về chương trình đào tạo nhân viên",
    slugVi: "thong-bao-ve-chuong-trinh-dao-tao-nhan-vien",
    titleEn: "Employee Training Program Notice",
    slugEn: "employee-training-program-notice",
    descriptionVi: "Chương trình đào tạo kỹ năng mềm cho nhân viên sẽ diễn ra vào tháng 2/2024...",
    descriptionEn: "Soft skills training program for employees will take place in February 2024...",
    contentVi: "Nội dung chi tiết thông báo đào tạo bằng tiếng Việt...",
    contentEn: "Detailed training notice content in English...",
    timePosted: "2024-01-10T00:00:00Z",
    status: 1,
    notificationCategoryId: 4,
    notificationCategoryNameVi: "Thông báo đào tạo",
    notificationCategoryNameEn: "Training Notice",
    notificationCategorySlugVi: "thong-bao-dao-tao",
    notificationCategorySlugEn: "training-notice",
    image: "https://picsum.photos/300/200?random=303"
  },
  {
    id: 4,
    titleVi: "Thông báo về cuộc họp định kỳ tháng 1",
    slugVi: "thong-bao-ve-cuoc-hop-dinh-ky-thang-1",
    titleEn: "January Regular Meeting Notice",
    slugEn: "january-regular-meeting-notice",
    descriptionVi: "Cuộc họp định kỳ tháng 1/2024 sẽ diễn ra vào ngày 25/1/2024 tại hội trường chính...",
    descriptionEn: "The January 2024 regular meeting will take place on January 25, 2024 at the main hall...",
    contentVi: "Nội dung chi tiết thông báo cuộc họp bằng tiếng Việt...",
    contentEn: "Detailed meeting notice content in English...",
    timePosted: "2024-01-05T00:00:00Z",
    status: 1,
    notificationCategoryId: 3,
    notificationCategoryNameVi: "Thông báo nội bộ",
    notificationCategoryNameEn: "Internal Notice",
    notificationCategorySlugVi: "thong-bao-noi-bo",
    notificationCategorySlugEn: "internal-notice",
    image: "https://picsum.photos/300/200?random=304"
  },
  {
    id: 5,
    titleVi: "Thông báo về chính sách bảo hiểm mới",
    slugVi: "thong-bao-ve-chinh-sach-bao-hiem-moi",
    titleEn: "New Insurance Policy Notice",
    slugEn: "new-insurance-policy-notice",
    descriptionVi: "Công ty đã cập nhật chính sách bảo hiểm sức khỏe cho nhân viên với nhiều quyền lợi mới...",
    descriptionEn: "The company has updated the health insurance policy for employees with many new benefits...",
    contentVi: "Nội dung chi tiết thông báo chính sách bảo hiểm bằng tiếng Việt...",
    contentEn: "Detailed insurance policy notice content in English...",
    timePosted: "2024-01-01T00:00:00Z",
    status: 1,
    notificationCategoryId: 3,
    notificationCategoryNameVi: "Thông báo nội bộ",
    notificationCategoryNameEn: "Internal Notice",
    notificationCategorySlugVi: "thong-bao-noi-bo",
    notificationCategorySlugEn: "internal-notice",
    image: "https://picsum.photos/300/200?random=305"
  },
  {
    id: 6,
    titleVi: "Thông báo mời thầu dự án CNS/ATM",
    slugVi: "thong-bao-moi-thau-du-an-cns-atm",
    titleEn: "CNS/ATM Project Tender Notice",
    slugEn: "cns-atm-project-tender-notice",
    descriptionVi: "Công ty mời thầu dự án CNS/ATM với giá trị ước tính 50 tỷ đồng...",
    descriptionEn: "The company invites tenders for CNS/ATM project with estimated value of 50 billion VND...",
    contentVi: "Nội dung chi tiết thông báo mời thầu bằng tiếng Việt...",
    contentEn: "Detailed tender notice content in English...",
    timePosted: "2024-02-01T00:00:00Z",
    status: 1,
    notificationCategoryId: 2,
    notificationCategoryNameVi: "Thông báo mời nhà cung cấp",
    notificationCategoryNameEn: "Supplier Notice",
    notificationCategorySlugVi: "moi-nha-cung-cap",
    notificationCategorySlugEn: "supplier-notice",
    image: "https://picsum.photos/300/200?random=306"
  },
  {
    id: 7,
    titleVi: "Thông báo về sự kiện kỷ niệm 20 năm thành lập",
    slugVi: "thong-bao-ve-su-kien-ky-niem-20-nam-thanh-lap",
    titleEn: "20th Anniversary Event Notice",
    slugEn: "20th-anniversary-event-notice",
    descriptionVi: "Sự kiện kỷ niệm 20 năm thành lập công ty sẽ diễn ra vào tháng 6/2024...",
    descriptionEn: "The company's 20th anniversary event will take place in June 2024...",
    contentVi: "Nội dung chi tiết thông báo sự kiện bằng tiếng Việt...",
    contentEn: "Detailed event notice content in English...",
    timePosted: "2024-03-01T00:00:00Z",
    status: 1,
    notificationCategoryId: 5,
    notificationCategoryNameVi: "Thông báo sự kiện",
    notificationCategoryNameEn: "Event Notice",
    notificationCategorySlugVi: "thong-bao-su-kien",
    notificationCategorySlugEn: "event-notice",
    image: "https://picsum.photos/300/200?random=307"
  },
  {
    id: 8,
    titleVi: "Thông báo về bảo mật thông tin mạng",
    slugVi: "thong-bao-ve-bao-mat-thong-tin-mang",
    titleEn: "Network Information Security Notice",
    slugEn: "network-information-security-notice",
    descriptionVi: "Công ty triển khai các biện pháp bảo mật thông tin mạng mới...",
    descriptionEn: "The company implements new network information security measures...",
    contentVi: "Nội dung chi tiết thông báo bảo mật bằng tiếng Việt...",
    contentEn: "Detailed security notice content in English...",
    timePosted: "2024-03-15T00:00:00Z",
    status: 1,
    notificationCategoryId: 6,
    notificationCategoryNameVi: "Thông báo bảo mật",
    notificationCategoryNameEn: "Security Notice",
    notificationCategorySlugVi: "thong-bao-bao-mat",
    notificationCategorySlugEn: "security-notice",
    image: "https://picsum.photos/300/200?random=308"
  }
]; 