export const mockNewsCategories = [
  {
    id: 10,
    titleVi: "Tin hoạt động",
    slugVi: "tin-hoat-dong",
    titleEn: "Activities",
    slugEn: "activities",
    descriptionVi: "Tin tức về các hoạt động và sự kiện của công ty",
    descriptionEn: "News about company activities and events",
    Status: 1,
  },
  {
    id: 11,
    titleVi: "Hoạt động công ty",
    slugVi: "hoat-dong-cong-ty",
    titleEn: "Company Activities",
    slugEn: "company-activities",
    descriptionVi: "Tin tức về các hoạt động nội bộ và sự kiện công ty",
    descriptionEn: "News about internal activities and company events",
    Status: 1,
  },
  {
    id: 12,
    titleVi: "Đảng bộ công ty",
    slugVi: "dang-bo-cong-ty",
    titleEn: "Company Party",
    slugEn: "company-party",
    descriptionVi: "Tin tức về hoạt động Đảng bộ và công đoàn",
    descriptionEn: "News about party committee and union activities",
    Status: 1,
  },
  {
    id: 13,
    titleVi: "Đoàn thanh niên công ty",
    slugVi: "doan-thanh-nien-cong-ty",
    titleEn: "Company Youth Union",
    slugEn: "company-youth-union",
    descriptionVi: "Tin tức về hoạt động Đoàn thanh niên",
    descriptionEn: "News about youth union activities",
    Status: 1,
  },
  {
    id: 14,
    titleVi: "Công đoàn công ty",
    slugVi: "cong-doan-cong-ty",
    titleEn: "Company Union",
    slugEn: "company-union",
    descriptionVi: "Tin tức về hoạt động công đoàn và phúc lợi",
    descriptionEn: "News about union activities and welfare",
    Status: 1,
  },
  {
    id: 15,
    titleVi: "Tin ngành hàng không",
    slugVi: "tin-nganh-hang-khong",
    titleEn: "Aviation News",
    slugEn: "aviation-news",
    descriptionVi: "Tin tức về ngành hàng không và CNS/ATM",
    descriptionEn: "News about aviation industry and CNS/ATM",
    Status: 1,
  },
  {
    id: 16,
    titleVi: "Tuyên truyền pháp luật",
    slugVi: "tuyen-truyen-phap-luat",
    titleEn: "Legal Propaganda",
    slugEn: "legal-propaganda",
    descriptionVi: "Tin tức về tuyên truyền pháp luật và quy định",
    descriptionEn: "News about legal propaganda and regulations",
    Status: 1,
  },
];
