// Mock data cho routes - sau này sẽ thay bằng API calls
export const mockRoutes = [
  {
    id: 1,
    path: '/',
    component: 'Home',
    layout: 'MainLayout',
    protected: false,
    parent_id: null,
    order_index: 1,
    is_active: true,
    labelVi: 'Trang chủ',
    labelEn: 'Home',
    icon: 'bi bi-house',
    descriptionVi: 'Trang chủ của website',
    descriptionEn: 'Website homepage'
  },
  {
    id: 2,
    path: '/news',
    component: 'NewsPage',
    layout: 'MainLayout',
    protected: false,
    parent_id: null,
    order_index: 2,
    is_active: true,
    labelVi: 'Tin tức',
    labelEn: 'News',
    icon: 'bi bi-newspaper',
    descriptionVi: 'Trang tin tức và hoạt động',
    descriptionEn: 'News and activities page'
  },
  {
    id: 3,
    path: '/news/:category',
    component: 'NewsListPage',
    layout: 'MainLayout',
    protected: false,
    parent_id: 2,
    order_index: 1,
    is_active: true,
    labelVi: 'Danh mục tin tức',
    labelEn: 'News Category',
    icon: 'bi bi-list',
    descriptionVi: 'Danh sách tin tức theo danh mục',
    descriptionEn: 'News list by category'
  },
  {
    id: 8,
    path: '/news/aviation',
    component: 'NewsListPage',
    layout: 'MainLayout',
    protected: false,
    parent_id: 2,
    order_index: 6,
    is_active: true,
    labelVi: 'Tin ngành hàng không',
    labelEn: 'Aviation News',
    icon: 'bi bi-airplane',
    descriptionVi: 'Tin tức về ngành hàng không',
    descriptionEn: 'Aviation industry news'
  },
  {
    id: 9,
    path: '/news/law',
    component: 'NewsListPage',
    layout: 'MainLayout',
    protected: false,
    parent_id: 2,
    order_index: 7,
    is_active: true,
    labelVi: 'Tuyên truyền pháp luật',
    labelEn: 'Legal Propaganda',
    icon: 'bi bi-journal-text',
    descriptionVi: 'Tuyên truyền pháp luật và quy định',
    descriptionEn: 'Legal propaganda and regulations'
  },
  {
    id: 10,
    path: '/news/:id/:slug',
    component: 'NewsDetailPage',
    layout: 'MainLayout',
    protected: false,
    parent_id: 2,
    order_index: 8,
    is_active: true,
    labelVi: 'Chi tiết tin tức',
    labelEn: 'News Detail',
    icon: 'bi bi-file-text',
    descriptionVi: 'Trang chi tiết tin tức',
    descriptionEn: 'News detail page'
  },
  {
    id: 11,
    path: '/products/*',
    component: 'ProductPage',
    layout: 'MainLayout',
    protected: false,
    parent_id: null,
    order_index: 3,
    is_active: true,
    labelVi: 'Sản phẩm',
    labelEn: 'Products',
    icon: 'bi bi-box',
    descriptionVi: 'Trang sản phẩm và giải pháp',
    descriptionEn: 'Products and solutions page'
  },
  {
    id: 12,
    path: '/services/*',
    component: 'ServicePage',
    layout: 'MainLayout',
    protected: false,
    parent_id: null,
    order_index: 4,
    is_active: true,
    labelVi: 'Dịch vụ',
    labelEn: 'Services',
    icon: 'bi bi-gear',
    descriptionVi: 'Trang dịch vụ và giải pháp',
    descriptionEn: 'Services and solutions page'
  },
  {
    id: 13,
    path: '/notifications',
    component: 'NotificationPage',
    layout: 'MainLayout',
    protected: false,
    parent_id: null,
    order_index: 5,
    is_active: true,
    labelVi: 'Thông báo',
    labelEn: 'Notifications',
    icon: 'bi bi-bell',
    descriptionVi: 'Trang thông báo và tuyển dụng',
    descriptionEn: 'Notifications and recruitment page'
  },
  {
    id: 14,
    path: '/notifications/:category',
    component: 'NotificationListPage',
    layout: 'MainLayout',
    protected: false,
    parent_id: 13,
    order_index: 1,
    is_active: true,
    labelVi: 'Danh sách thông báo',
    labelEn: 'Notification List',
    icon: 'bi bi-list',
    descriptionVi: 'Danh sách thông báo theo danh mục',
    descriptionEn: 'Notification list by category'
  },
  {
    id: 15,
    path: '/notifications/:id/:slug',
    component: 'NotificationDetailPage',
    layout: 'MainLayout',
    protected: false,
    parent_id: 13,
    order_index: 2,
    is_active: true,
    labelVi: 'Chi tiết thông báo',
    labelEn: 'Notification Detail',
    icon: 'bi bi-file-text',
    descriptionVi: 'Trang chi tiết thông báo',
    descriptionEn: 'Notification detail page'
  },
  {
    id: 16,
    path: '/company',
    component: 'Financial',
    layout: 'MainLayout',
    protected: false,
    parent_id: null,
    order_index: 6,
    is_active: true,
    labelVi: 'Thông tin công ty',
    labelEn: 'Company Information',
    icon: 'bi bi-building',
    descriptionVi: 'Trang thông tin về công ty',
    descriptionEn: 'Company information page'
  },
  {
    id: 17,
    path: '/company/finance',
    component: 'Financial',
    layout: 'MainLayout',
    protected: false,
    parent_id: 16,
    order_index: 1,
    is_active: true,
    labelVi: 'Thông tin tài chính',
    labelEn: 'Financial Information',
    icon: 'bi bi-cash-stack',
    descriptionVi: 'Thông tin tài chính công ty',
    descriptionEn: 'Company financial information'
  },
  {
    id: 18,
    path: '/company/history',
    component: 'History',
    layout: 'MainLayout',
    protected: false,
    parent_id: 16,
    order_index: 2,
    is_active: true,
    labelVi: 'Lịch sử ra đời',
    labelEn: 'Company History',
    icon: 'bi bi-clock-history',
    descriptionVi: 'Lịch sử phát triển công ty',
    descriptionEn: 'Company development history'
  },
  {
    id: 19,
    path: '/company/structure',
    component: 'Structure',
    layout: 'MainLayout',
    protected: false,
    parent_id: 16,
    order_index: 3,
    is_active: true,
    labelVi: 'Cơ cấu tổ chức',
    labelEn: 'Organization Structure',
    icon: 'bi bi-diagram-3',
    descriptionVi: 'Cơ cấu tổ chức công ty',
    descriptionEn: 'Company organization structure'
  },
  {
    id: 20,
    path: '/company/leadership',
    component: 'Leadership',
    layout: 'MainLayout',
    protected: false,
    parent_id: 16,
    order_index: 4,
    is_active: true,
    labelVi: 'Ban lãnh đạo',
    labelEn: 'Leadership',
    icon: 'bi bi-person-badge',
    descriptionVi: 'Thông tin ban lãnh đạo công ty',
    descriptionEn: 'Company leadership information'
  },
  {
    id: 21,
    path: '/company/business',
    component: 'Business',
    layout: 'MainLayout',
    protected: false,
    parent_id: 16,
    order_index: 5,
    is_active: true,
    labelVi: 'Ngành nghề kinh doanh',
    labelEn: 'Business Sectors',
    icon: 'bi bi-briefcase',
    descriptionVi: 'Thông tin ngành nghề kinh doanh',
    descriptionEn: 'Business sectors information'
  },
  {
    id: 22,
    path: '/company/iso',
    component: 'Iso',
    layout: 'MainLayout',
    protected: false,
    parent_id: 16,
    order_index: 6,
    is_active: true,
    labelVi: 'Hệ thống chứng chỉ ISO',
    labelEn: 'ISO Certification System',
    icon: 'bi bi-award',
    descriptionVi: 'Hệ thống chứng chỉ ISO của công ty',
    descriptionEn: 'Company ISO certification system'
  },
  {
    id: 23,
    path: '/company/gallery',
    component: 'Gallery',
    layout: 'MainLayout',
    protected: false,
    parent_id: 16,
    order_index: 7,
    is_active: true,
    labelVi: 'Thư viện công ty',
    labelEn: 'Company Gallery',
    icon: 'bi bi-images',
    descriptionVi: 'Thư viện hình ảnh công ty',
    descriptionEn: 'Company image gallery'
  },
  {
    id: 24,
    path: '/contact',
    component: 'ContactPage',
    layout: 'MainLayout',
    protected: false,
    parent_id: null,
    order_index: 7,
    is_active: true,
    labelVi: 'Liên hệ',
    labelEn: 'Contact',
    icon: 'bi bi-envelope',
    descriptionVi: 'Trang liên hệ và thông tin',
    descriptionEn: 'Contact and information page'
  },
  {
    id: 25,
    path: '/login',
    component: 'UserLogin',
    layout: null,
    protected: false,
    parent_id: null,
    order_index: 8,
    is_active: true,
    labelVi: 'Đăng nhập',
    labelEn: 'Login',
    icon: 'bi bi-box-arrow-in-right',
    descriptionVi: 'Trang đăng nhập hệ thống',
    descriptionEn: 'System login page'
  },
  {
    id: 26,
    path: '*',
    component: 'NotFoundPage',
    layout: null,
    protected: false,
    parent_id: null,
    order_index: 999,
    is_active: true,
    labelVi: 'Không tìm thấy',
    labelEn: 'Not Found',
    icon: 'bi bi-exclamation-triangle',
    descriptionVi: 'Trang lỗi không tìm thấy',
    descriptionEn: 'Page not found error'
  }
]; 