export const mockNotificationCategories = [
  {
    id: 1,
    titleVi: "Tuyển dụng",
    slugVi: "tuyen-dung",
    titleEn: "Recruitment",
    slugEn: "recruitment",
    descriptionVi: "Thông báo tuyển dụng và cơ hội nghề nghiệp",
    descriptionEn: "Recruitment notices and career opportunities",
    Status: 1,
  },
  {
    id: 2,
    titleVi: "Thông báo mời nhà cung cấp",
    slugVi: "moi-nha-cung-cap",
    titleEn: "Supplier Notice",
    slugEn: "supplier-notice",
    descriptionVi: "Thông báo mời thầu và nhà cung cấp",
    descriptionEn: "Tender notices and supplier information",
    Status: 1,
  },
  {
    id: 3,
    titleVi: "Thông báo khác",
    slugVi: "thong-bao-khac",
    titleEn: "Other Notices",
    slugEn: "other-notices",
    descriptionVi: "Các thông báo khác và thông tin chung",
    descriptionEn: "Other notices and general information",
    Status: 1,
  },
];
