export const mockProductCategories = [
  {
    id: 1,
    nameVi: "CNS/ATM",
    slugVi: "cns-atm",
    nameEn: "CNS/ATM",
    slugEn: "cns-atm",
    descriptionVi: "Hệ thống thông tin dẫn đường giám sát và quản lý không lưu",
    descriptionEn:
      "Communication, Navigation, Surveillance and Air Traffic Management systems",
    status: 1,
  },
  {
    id: 2,
    nameVi: "Hệ thống đèn hiệu",
    slugVi: "he-thong-den-hieu",
    nameEn: "Lighting System",
    slugEn: "lighting-system",
    descriptionVi:
      "Hệ thống đèn hiệu sân bay và thiết bị chiếu sáng hàng không",
    descriptionEn: "Airport lighting systems and aviation lighting equipment",
    status: 1,
  },
  {
    id: 3,
    nameVi: "Shelter",
    slugVi: "shelter",
    nameEn: "Shelter",
    slugEn: "shelter",
    descriptionVi: "",
    descriptionEn: "",
    status: 1,
  },
  {
    id: 4,
    nameVi: "Bàn console",
    slugVi: "ban-console",
    nameEn: "Console Desk",
    slugEn: "console-desk",
    descriptionVi: "",
    descriptionEn: "",
    status: 1,
  },
  {
    id: 5,
    nameVi: "Giàn phản xạ",
    slugVi: "gian-phan-xa",
    nameEn: "Counterpoise",
    slugEn: "counterpoise",
    descriptionVi: "",
    descriptionEn: "",
    status: 1,
  },
  {
    id: 6,
    nameVi: "Thiết bị ghi âm/ ghi hình",
    slugVi: "ghi-am-ghi-hinh",
    nameEn: "Recording/video equipment",
    slugEn: "audio-video-recording",
    descriptionVi: "",
    descriptionEn: "",
    status: 1,
  },
  {
    id: 7,
    nameVi: "Thiết bị dân dụng khác",
    slugVi: "thiet-bi-dan-dung-khac",
    nameEn: "Other Equipment",
    slugEn: "other-equipment",
    descriptionVi: "",
    descriptionEn: "",
    status: 1,
  },
];
