export const mockServices = [
  {
    id: 1,
    titleVi: "Dịch vụ thông tin dẫn đường giám sát (CNS)",
    titleEn: "CNS Service",
    slugVi: "thong-tin-dan-duong-giam-sat",
    slugEn: "cns-service",
    descriptionVi: "",
    descriptionEn: "",
    contentVi: ``,
    contentEn: ``,
    timePosted: "2024-01-10T00:00:00Z",
    status: 1,
    image:
      "https://attech.com.vn/wp-content/uploads/2015/02/DV-ky-thuat-CNS-s.jpg",
  },
  {
    id: 2,
    titleVi: "Dịch vụ Bay kiểm tra hiệu chuẩn",
    titleEn: "Calibration Service",
    slugVi: "bay-kiem-tra-hieu-chuan",
    slugEn: "calibration-service",
    descriptionVi: "",
    descriptionEn: "",
    contentVi: ``,
    contentEn: ``,
    timePosted: "2024-01-15T00:00:00Z",
    status: 1,
    image: "https://attech.com.vn/wp-content/uploads/2015/02/DV-BHC1.jpg",
  },
  {
    id: 3,
    titleVi: "Dịch vụ Thử nghiệm - Hiệu chuẩn",
    titleEn: "Testing - Calibration Service",
    slugVi: "thu-nghiem-hieu-chuan",
    slugEn: "testing-calibration-service",
    descriptionVi: "",
    descriptionEn: "",
    contentVi: ``,
    contentEn: ``,
    timePosted: "2024-01-20T00:00:00Z",
    status: 1,
    image: "/assets/images/thu-nghiem-hieu-chuan/thu-nghiem-hieu-chuan.jpg",
  },
  {
    id: 4,
    titleVi: "Dịch vụ Kỹ thuật (Hàng không)",
    titleEn: "Aviation Service",
    slugVi: "ky-thuat-hang-khong",
    slugEn: "aviation-service",
    descriptionVi: "",
    descriptionEn: "",
    contentVi: ``,
    contentEn: ``,
    timePosted: "2024-02-01T00:00:00Z",
    status: 1,
    image: "https://attech.com.vn/wp-content/uploads/2015/02/DV-HK.jpg",
  },
  {
    id: 5,
    titleVi: "Dịch vụ Huấn luyện - Đào tạo",
    titleEn: "Training - Education Service",
    slugVi: "huan-luyen-dao-tao",
    slugEn: "training-education-service",
    descriptionVi: "",
    descriptionEn: "",
    contentVi: ``,
    contentEn: ``,
    timePosted: "2024-02-15T00:00:00Z",
    status: 1,
    image: "/assets/images/hldt/dich-vu-hldt-1.jpg",
  },
  {
    id: 6,
    titleVi: "Dịch vụ Tư vấn đầu tư và xây dựng QLDA",
    titleEn: "Consulting - QLDA Service",
    slugVi: "tu-van-dau-tu-xay-dung-qlda",
    slugEn: "consulting-qlda-service",
    descriptionVi: "",
    descriptionEn: "",
    contentVi: ``,
    contentEn: ``,
    timePosted: "2024-03-01T00:00:00Z",
    status: 1,
    image: "https://attech.com.vn/wp-content/uploads/2015/02/TVTK-anhs.jpg",
  },
];
