export const mockProducts = [
  {
    id: 1,
    nameVi: "Hệ thống ADS-B",
    slugVi: "he-thong-ads-b",
    nameEn: "ADS-B System",
    slugEn: "ads-b-system",
    descriptionVi: "Hệ thống giám sát tự động phụ thuộc quảng bá với độ chính xác cao...",
    descriptionEn: "Automatic Dependent Surveillance-Broadcast system with high accuracy...",
    contentVi: "Nội dung chi tiết hệ thống ADS-B bằng tiếng Việt...",
    contentEn: "Detailed ADS-B system content in English...",
    timePosted: "2024-01-15T00:00:00Z",
    status: 1,
    productCategoryId: 1,
    productCategoryNameVi: "CNS/ATM",
    productCategoryNameEn: "CNS/ATM",
    productCategorySlugVi: "cns-atm",
    productCategorySlugEn: "cns-atm",
    image: "https://picsum.photos/300/200?random=101"
  },
  {
    id: 2,
    nameVi: "Phần mềm quản lý sân bay",
    slugVi: "phan-mem-quan-ly-san-bay",
    nameEn: "Airport Management Software",
    slugEn: "airport-management-software",
    descriptionVi: "Giải pháp quản lý toàn diện cho các sân bay với khả năng mở rộng cao...",
    descriptionEn: "Comprehensive management solution for airports with high scalability...",
    contentVi: "Nội dung chi tiết phần mềm quản lý sân bay bằng tiếng Việt...",
    contentEn: "Detailed content for airport management software in English...",
    timePosted: "2024-01-20T00:00:00Z",
    status: 1,
    productCategoryId: 6,
    productCategoryNameVi: "Phần mềm quản lý",
    productCategoryNameEn: "Management Software",
    productCategorySlugVi: "phan-mem-quan-ly",
    productCategorySlugEn: "management-software",
    image: "https://picsum.photos/400/300?random=2"
  },
  {
    id: 3,
    nameVi: "Thiết bị giám sát không lưu",
    slugVi: "thiet-bi-giam-sat-khong-luu",
    nameEn: "Air Traffic Surveillance Device",
    slugEn: "air-traffic-surveillance-device",
    descriptionVi: "Thiết bị giám sát không lưu hiện đại với độ chính xác cao và khả năng hoạt động 24/7...",
    descriptionEn: "Modern air traffic surveillance device with high accuracy and 24/7 operation...",
    contentVi: "Nội dung chi tiết thiết bị giám sát không lưu bằng tiếng Việt...",
    contentEn: "Detailed content for air traffic surveillance device in English...",
    timePosted: "2024-02-01T00:00:00Z",
    status: 1,
    productCategoryId: 3,
    productCategoryNameVi: "Thiết bị giám sát",
    productCategoryNameEn: "Surveillance Equipment",
    productCategorySlugVi: "thiet-bi-giam-sat",
    productCategorySlugEn: "surveillance-equipment",
    image: "https://picsum.photos/400/300?random=3"
  },
  {
    id: 4,
    nameVi: "Hệ thống thông tin hàng không",
    slugVi: "he-thong-thong-tin-hang-khong",
    nameEn: "Aviation Information System",
    slugEn: "aviation-information-system",
    descriptionVi: "Hệ thống thông tin hàng không tích hợp với các tiêu chuẩn quốc tế...",
    descriptionEn: "Aviation information system integrated with international standards...",
    contentVi: "Nội dung chi tiết hệ thống thông tin hàng không bằng tiếng Việt...",
    contentEn: "Detailed content for aviation information system in English...",
    timePosted: "2024-02-15T00:00:00Z",
    status: 1,
    productCategoryId: 4,
    productCategoryNameVi: "Hệ thống thông tin",
    productCategoryNameEn: "Information System",
    productCategorySlugVi: "he-thong-thong-tin",
    productCategorySlugEn: "information-system",
    image: "https://picsum.photos/400/300?random=4"
  },
  {
    id: 5,
    nameVi: "Giải pháp bảo mật mạng",
    slugVi: "giai-phap-bao-mat-mang",
    nameEn: "Network Security Solution",
    slugEn: "network-security-solution",
    descriptionVi: "Giải pháp bảo mật mạng toàn diện cho các tổ chức hàng không...",
    descriptionEn: "Comprehensive network security solution for aviation organizations...",
    contentVi: "Nội dung chi tiết giải pháp bảo mật mạng bằng tiếng Việt...",
    contentEn: "Detailed content for network security solution in English...",
    timePosted: "2024-03-01T00:00:00Z",
    status: 1,
    productCategoryId: 5,
    productCategoryNameVi: "Bảo mật mạng",
    productCategoryNameEn: "Network Security",
    productCategorySlugVi: "bao-mat-mang",
    productCategorySlugEn: "network-security",
    image: "https://picsum.photos/400/300?random=5"
  },
  {
    id: 6,
    nameVi: "Hệ thống đèn hiệu sân bay",
    slugVi: "he-thong-den-hieu-san-bay",
    nameEn: "Airport Lighting System",
    slugEn: "airport-lighting-system",
    descriptionVi: "Hệ thống đèn hiệu sân bay hiện đại với công nghệ LED tiên tiến...",
    descriptionEn: "Modern airport lighting system with advanced LED technology...",
    contentVi: "Nội dung chi tiết hệ thống đèn hiệu sân bay bằng tiếng Việt...",
    contentEn: "Detailed content for airport lighting system in English...",
    timePosted: "2024-03-15T00:00:00Z",
    status: 1,
    productCategoryId: 2,
    productCategoryNameVi: "Hệ thống đèn hiệu",
    productCategoryNameEn: "Lighting System",
    productCategorySlugVi: "he-thong-den-hieu",
    productCategorySlugEn: "lighting-system",
    image: "https://picsum.photos/400/300?random=6"
  },
  {
    id: 7,
    nameVi: "Thiết bị đo lường chuyên dụng",
    slugVi: "thiet-bi-do-luong-chuyen-dung",
    nameEn: "Specialized Measuring Equipment",
    slugEn: "specialized-measuring-equipment",
    descriptionVi: "Thiết bị đo lường và hiệu chuẩn chuyên dụng cho ngành hàng không...",
    descriptionEn: "Specialized measuring and calibration equipment for aviation industry...",
    contentVi: "Nội dung chi tiết thiết bị đo lường chuyên dụng bằng tiếng Việt...",
    contentEn: "Detailed content for specialized measuring equipment in English...",
    timePosted: "2024-04-01T00:00:00Z",
    status: 1,
    productCategoryId: 7,
    productCategoryNameVi: "Thiết bị đo lường",
    productCategoryNameEn: "Measuring Equipment",
    productCategorySlugVi: "thiet-bi-do-luong",
    productCategorySlugEn: "measuring-equipment",
    image: "https://picsum.photos/400/300?random=7"
  },
  {
    id: 8,
    nameVi: "Hệ thống điều khiển tự động",
    slugVi: "he-thong-dieu-khien-tu-dong",
    nameEn: "Automatic Control System",
    slugEn: "automatic-control-system",
    descriptionVi: "Hệ thống điều khiển tự động cho các thiết bị hàng không...",
    descriptionEn: "Automatic control system for aviation equipment...",
    contentVi: "Nội dung chi tiết hệ thống điều khiển tự động bằng tiếng Việt...",
    contentEn: "Detailed content for automatic control system in English...",
    timePosted: "2024-04-15T00:00:00Z",
    status: 1,
    productCategoryId: 8,
    productCategoryNameVi: "Hệ thống điều khiển",
    productCategoryNameEn: "Control System",
    productCategorySlugVi: "he-thong-dieu-khien",
    productCategorySlugEn: "control-system",
    image: "https://picsum.photos/400/300?random=8"
  }
]; 