export const mockServices = [
  {
    id: 1,
    nameVi: "Dịch vụ thông tin dẫn đường giám sát (CNS)",
    nameEn: "CNS Service",
    slugVi: "thong-tin-dan-duong-giam-sat",
    slugEn: "cns-service",
    descriptionVi: "Dịch vụ CNS phục vụ điều hành bay, kỹ thuật và huấn luyện chuyên ngành.",
    descriptionEn: "CNS services for flight operation, technical and training.",
    contentVi: `<div class='service-header'><h1>Dịch vụ CNS</h1><p>Chi tiết dịch vụ CNS bằng tiếng Việt...</p></div>`,
    contentEn: `<div class='service-header'><h1>CNS Service</h1><p>CNS service details in English...</p></div>`,
    timePosted: "2024-01-10T00:00:00Z",
    status: 1,
    serviceCategoryId: 1,
    serviceCategoryNameVi: "Dịch vụ hàng không",
    serviceCategoryNameEn: "Aviation Service",
    serviceCategorySlugVi: "dich-vu-hang-khong",
    serviceCategorySlugEn: "aviation-service",
    image: "https://attech.com.vn/wp-content/uploads/2015/02/DV-ky-thuat-CNS-s.jpg"
  },
  {
    id: 2,
    nameVi: "Dịch vụ Bay kiểm tra hiệu chuẩn",
    nameEn: "Calibration Service",
    slugVi: "bay-kiem-tra-hieu-chuan",
    slugEn: "calibration-service",
    descriptionVi: "Dịch vụ bay kiểm tra hiệu chuẩn các thiết bị dẫn đường giám sát hàng không.",
    descriptionEn: "Calibration flight service for navigation and surveillance equipment.",
    contentVi: `<div class='service-header'><h1>Bay kiểm tra hiệu chuẩn</h1><p>Chi tiết dịch vụ bay kiểm tra hiệu chuẩn bằng tiếng Việt...</p></div>`,
    contentEn: `<div class='service-header'><h1>Calibration Service</h1><p>Calibration service details in English...</p></div>`,
    timePosted: "2024-01-15T00:00:00Z",
    status: 1,
    serviceCategoryId: 6,
    serviceCategoryNameVi: "Dịch vụ bay kiểm tra",
    serviceCategoryNameEn: "Flight Inspection Service",
    serviceCategorySlugVi: "dich-vu-bay-kiem-tra",
    serviceCategorySlugEn: "flight-inspection-service",
    image: "https://attech.com.vn/wp-content/uploads/2015/02/DV-BHC1.jpg"
  },
  {
    id: 3,
    nameVi: "Dịch vụ Thử nghiệm - Hiệu chuẩn",
    nameEn: "Testing - Calibration Service",
    slugVi: "thu-nghiem-hieu-chuan",
    slugEn: "testing-calibration-service",
    descriptionVi: "Dịch vụ thử nghiệm, hiệu chuẩn thiết bị đo lường, môi trường, quang học.",
    descriptionEn: "Testing and calibration services for measuring, environmental, and optical equipment.",
    contentVi: `<div class='service-header'><h1>Thử nghiệm - Hiệu chuẩn</h1><p>Chi tiết dịch vụ thử nghiệm - hiệu chuẩn bằng tiếng Việt...</p></div>`,
    contentEn: `<div class='service-header'><h1>Testing - Calibration Service</h1><p>Testing - calibration service details in English...</p></div>`,
    timePosted: "2024-01-20T00:00:00Z",
    status: 1,
    serviceCategoryId: 3,
    serviceCategoryNameVi: "Dịch vụ thử nghiệm",
    serviceCategoryNameEn: "Testing Service",
    serviceCategorySlugVi: "dich-vu-thu-nghiem",
    serviceCategorySlugEn: "testing-service",
    image: "https://attech.com.vn/wp-content/uploads/2015/02/anh-thu-nghiem-hieu-chuan-2019.jpg"
  },
  {
    id: 4,
    nameVi: "Dịch vụ Kỹ thuật (Hàng không)",
    nameEn: "Aviation Service",
    slugVi: "ky-thuat-hang-khong",
    slugEn: "aviation-service",
    descriptionVi: "Dịch vụ kỹ thuật chuyên ngành hàng không.",
    descriptionEn: "Technical services for aviation sector.",
    contentVi: `<div class='service-header'><h1>Kỹ thuật Hàng không</h1><p>Chi tiết dịch vụ kỹ thuật hàng không bằng tiếng Việt...</p></div>`,
    contentEn: `<div class='service-header'><h1>Aviation Service</h1><p>Aviation service details in English...</p></div>`,
    timePosted: "2024-02-01T00:00:00Z",
    status: 1,
    serviceCategoryId: 2,
    serviceCategoryNameVi: "Dịch vụ kỹ thuật",
    serviceCategoryNameEn: "Technical Service",
    serviceCategorySlugVi: "dich-vu-ky-thuat",
    serviceCategorySlugEn: "technical-service",
    image: "https://attech.com.vn/wp-content/uploads/2015/02/DV-HK.jpg"
  },
  {
    id: 5,
    nameVi: "Dịch vụ Huấn luyện - Đào tạo",
    nameEn: "Training - Education Service",
    slugVi: "huan-luyen-dao-tao",
    slugEn: "training-education-service",
    descriptionVi: "Dịch vụ huấn luyện, đào tạo chuyên ngành CNS.",
    descriptionEn: "Training and education services for CNS sector.",
    contentVi: `<div class='service-header'><h1>Huấn luyện - Đào tạo</h1><p>Chi tiết dịch vụ huấn luyện - đào tạo bằng tiếng Việt...</p></div>`,
    contentEn: `<div class='service-header'><h1>Training - Education Service</h1><p>Training - education service details in English...</p></div>`,
    timePosted: "2024-02-15T00:00:00Z",
    status: 1,
    serviceCategoryId: 4,
    serviceCategoryNameVi: "Dịch vụ đào tạo",
    serviceCategoryNameEn: "Training Service",
    serviceCategorySlugVi: "dich-vu-dao-tao",
    serviceCategorySlugEn: "training-service",
    image: "https://attech.com.vn/wp-content/uploads/2015/02/DV-HLDT-small.jpg"
  },
  {
    id: 6,
    nameVi: "Dịch vụ Tư vấn đầu tư và xây dựng QLDA",
    nameEn: "Consulting - QLDA Service",
    slugVi: "tu-van-dau-tu-xay-dung-qlda",
    slugEn: "consulting-qlda-service",
    descriptionVi: "Dịch vụ tư vấn đầu tư xây dựng và quản lý dự án.",
    descriptionEn: "Consulting and project management services.",
    contentVi: `<div class='service-header'><h1>Tư vấn đầu tư và xây dựng QLDA</h1><p>Chi tiết dịch vụ tư vấn đầu tư và xây dựng QLDA bằng tiếng Việt...</p></div>`,
    contentEn: `<div class='service-header'><h1>Consulting - QLDA Service</h1><p>Consulting - QLDA service details in English...</p></div>`,
    timePosted: "2024-03-01T00:00:00Z",
    status: 1,
    serviceCategoryId: 5,
    serviceCategoryNameVi: "Dịch vụ tư vấn",
    serviceCategoryNameEn: "Consulting Service",
    serviceCategorySlugVi: "dich-vu-tu-van",
    serviceCategorySlugEn: "consulting-service",
    image: "https://attech.com.vn/wp-content/uploads/2015/02/TVTK-anhs.jpg"
  },
  {
    id: 7,
    nameVi: "Dịch vụ Bảo trì thiết bị",
    nameEn: "Equipment Maintenance Service",
    slugVi: "bao-tri-thiet-bi",
    slugEn: "equipment-maintenance-service",
    descriptionVi: "Dịch vụ bảo trì và sửa chữa thiết bị hàng không chuyên nghiệp.",
    descriptionEn: "Professional maintenance and repair services for aviation equipment.",
    contentVi: `<div class='service-header'><h1>Bảo trì thiết bị</h1><p>Chi tiết dịch vụ bảo trì thiết bị bằng tiếng Việt...</p></div>`,
    contentEn: `<div class='service-header'><h1>Equipment Maintenance Service</h1><p>Equipment maintenance service details in English...</p></div>`,
    timePosted: "2024-03-15T00:00:00Z",
    status: 1,
    serviceCategoryId: 7,
    serviceCategoryNameVi: "Dịch vụ bảo trì",
    serviceCategoryNameEn: "Maintenance Service",
    serviceCategorySlugVi: "dich-vu-bao-tri",
    serviceCategorySlugEn: "maintenance-service",
    image: "https://picsum.photos/400/300?random=7"
  },
  {
    id: 8,
    nameVi: "Dịch vụ Hỗ trợ kỹ thuật",
    nameEn: "Technical Support Service",
    slugVi: "ho-tro-ky-thuat",
    slugEn: "technical-support-service",
    descriptionVi: "Dịch vụ hỗ trợ kỹ thuật và vận hành hệ thống hàng không.",
    descriptionEn: "Technical support and aviation system operation services.",
    contentVi: `<div class='service-header'><h1>Hỗ trợ kỹ thuật</h1><p>Chi tiết dịch vụ hỗ trợ kỹ thuật bằng tiếng Việt...</p></div>`,
    contentEn: `<div class='service-header'><h1>Technical Support Service</h1><p>Technical support service details in English...</p></div>`,
    timePosted: "2024-04-01T00:00:00Z",
    status: 1,
    serviceCategoryId: 8,
    serviceCategoryNameVi: "Dịch vụ hỗ trợ",
    serviceCategoryNameEn: "Support Service",
    serviceCategorySlugVi: "dich-vu-ho-tro",
    serviceCategorySlugEn: "support-service",
    image: "https://picsum.photos/400/300?random=8"
  }
]; 